main/urls.py
from django.urls import path
from django.contrib.auth.decorators import user_passes_test
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('servises/', views.servises, name='servises'),
    path('order/', views.BasicUploadView.as_view(), name='order'),
    path('<int:id>/delete/', views.delete_photo, name='delete'),
    path('order/confirm/', views.edit_upload_form, name='confirm'),
    path('complite/', views.OrderComplite.as_view(), name='complite'),
    path('added-order/', views.confirm_order, name='added-order'),
    path('portfolio/', views.portfolio, name='portfolio'),
]

photo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('main.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import ProductsViewsDetail, ProductsViewsList, ProductViewsCategory


app_name = 'shop'

urlpatterns = [
    path('product/', ProductsViewsList.as_view(), name='product'),
    path('product/<int:id>', ProductsViewsDetail.as_view(), name='detail'),
    path('product/<category>', ProductViewsCategory.as_view(), name='category'),
]

shop/models.py
from django.db import models
from django.db.models.deletion import CASCADE


class ShopCardModel(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование товара')
    description = models.CharField(
        max_length=1000, verbose_name='Описание товара', null=True, blank=True)
    category = models.CharField(
        max_length=100, verbose_name='Категория товара', null=False)
    price = models.PositiveBigIntegerField(
        blank=True, null=True, verbose_name='Цена')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Товар в магазине'
        verbose_name_plural = 'Товар в магазине'


class ShopCardPhotos(models.Model):
    show = models.ForeignKey(
        ShopCardModel, on_delete=models.CASCADE, related_name="shop_images"
    )
    photo = models.ImageField(
        verbose_name='Изображение товара', upload_to='shop-photos')

main/forms.py
from django import forms
from django.core.validators import validate_image_file_extension
from django.utils.translation import gettext as _
from .models import Photo, Portfolio, PortfolioPhoto


class PhotoForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ('file', 'format', 'count', 'papier',)


class PortfolioAdminForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = (
            "photo_title",
        )

    def clean_photos(self):
        """Make sure only images can be uploaded."""
        for upload in self.files.getlist("images"):
            validate_image_file_extension(upload)

    def save_photos(self, showphoto):
        """Process each uploaded image."""
        for upload in self.files.getlist("images"):
            photo = PortfolioPhoto(showphoto=showphoto, photo=upload)
            photo.save()

shop/forms.py
from django import forms
from django.core.validators import validate_image_file_extension
from django.utils.translation import gettext as _


from .models import ShopCardModel, ShopCardPhotos


class ShopAdminForm(forms.ModelForm):
    class Meta:
        model = ShopCardModel
        fields = (
            "name",
            "description",
            "category",
            "price",
        )

    def clean_photos(self):
        """Make sure only images can be uploaded."""
        for upload in self.files.getlist("shop_images"):
            validate_image_file_extension(upload)

    def save_photos(self, show):
        """Process each uploaded image."""
        for upload in self.files.getlist("shop_images"):
            photo = ShopCardPhotos(show=show, photo=upload)
            photo.save()

main/views.py
import logging
from emails.email import SendingEmail
import os
from django.http.response import HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from django.http import JsonResponse
from django.views import View
from datetime import datetime

from user.models import UserModel


from .models import MainCardModel, Photo, Orders, Portfolio, PortfolioPhoto, Services, ConfirmOrder
from .forms import PhotoForm
from .sorting import moveFiles


log = logging.getLogger(__name__)


def index(request):
    card = MainCardModel.objects.all()
    context = {
        'card': card
    }
    return render(request, 'main/index.html', context)


def servises(request):
    card = MainCardModel.objects.all()
    context = {
        'card': card
    }
    return render(request, 'main/servises.html', context)


def portfolio(request):
    photo_cat = Portfolio.objects.all()
    photos = PortfolioPhoto.objects.all()
    return render(request, 'main/portfolio.html', {'photo_cat': photo_cat, 'photos': photos})


class OrderView(View):
    def get(request):
        photo_list = Photo.get_user_photos(request)
        order_session_key = request.session.session_key
        order = Orders.get_order_photos(request)
        order.delete()
        temp_order = []

        for photo in photo_list:
            temp_order_photo = []
            order_format = photo.format
            order_papier = photo.papier
            order_session_key = photo.session_key
            order_user_id = photo.user
            temp_order_photo.append(order_format)
            temp_order_photo.append(order_papier)
            temp_order_photo.append(order_session_key)
            temp_order_photo.append(order_user_id)
            temp_order_count = photo.count
            if temp_order_photo not in temp_order:
                temp_order.append(temp_order_photo)
                order = Orders(order_format=order_format,
                               order_papier=order_papier, order_count=temp_order_count, order_session_key=order_session_key, user=order_user_id)
                order.save()
            else:
                temp = Photo.get_user_photos(request).filter(
                    format=temp_order_photo[0], papier=temp_order_photo[1], session_key=temp_order_photo[2], user=temp_order_photo[3])
                temp_count = 0
                for i in temp:
                    temp_count += i.count
                order = Orders.objects.filter(
                    order_format=temp_order_photo[0], order_papier=temp_order_photo[1], order_session_key=temp_order_photo[2], user=temp_order_photo[3])
                order.update(order_count=temp_count)


def delete_photo(request, id):
    temp_photo = Photo.get_user_photos(request).filter(id=id)

    if not temp_photo.exists():
        log.info('Can`t find your photo with this id')
        return HttpResponseNotFound('Can`t find your photo with this id')

    log.info('Photo "%s" was deleted to order', temp_photo[0])

    temp_photo.delete()
    OrderView.get(request)

    return HttpResponse('Photo deleted')


def edit_upload_form(request):
    temp_photo = Photo.get_user_photos(request).filter(id=request.POST['id'])
    if 'format' in request.POST:
        format_edit = request.POST['format']

        temp_photo.update(format=format_edit)
        OrderView.get(request)

        log.info('Photo "%s" was changed to order', temp_photo[0])
        return HttpResponse('Photo updated')

    if 'count' in request.POST:
        count_edit = request.POST['count']

        temp_photo.update(count=count_edit)
        OrderView.get(request)

        log.info('Photo "%s" was changed to order', temp_photo[0])
        return HttpResponse('Photo updated')

    if 'papier' in request.POST:
        papier_edit = request.POST['papier']

        temp_photo.update(papier=papier_edit)
        OrderView.get(request)

        log.info('Photo "%s" was changed to order', temp_photo[0])
        return HttpResponse('Photo updated')


class BasicUploadView(View):
    def get(self, request):
        photos_list = Photo.get_user_photos(request).order_by('-uploaded_at')
        OrderView.get(request)
        return render(self.request, 'main/order.html', {
            'photos': photos_list,
            'service_data': Services.to_json(),
        })

    def post(self, request):
        form = PhotoForm(self.request.POST, self.request.FILES)

        if form.is_valid():
            photo = form.save(commit=False)
            if request.user.is_anonymous:
                photo.session_key = request.session.session_key
            else:
                photo.user = request.user
            photo.session_key = request.session.session_key
            photo.save()

            log.info('Photos added to order for user:" %s"', photo.user)

            OrderView.get(request)

            data = {
                'is_valid': True,
                'name': photo.file.name,
                'url': photo.file.url,
                'id': photo.id,
                'count': photo.count,
                'papier': photo.papier,
                'format': photo.FORMATS,
                'service_data': Services.to_json(),
            }
        else:
            data = {'is_valid': False, 'errors': form.errors.as_text()}
        return JsonResponse(data)


class OrderComplite(View):
    def get(self, request):
        order_list = Orders.get_order_photos(
            request).values('order_format', 'order_count', 'order_papier')
        cost_list = Services.objects.all().values('name', 'cost')
        # user_info = UserModel.get_user_info(
        #     request).values('first_name', 'phone', 'city')
        user_info = UserModel.objects.all().filter(id=request.user.id)

        price = 0
        for i in order_list:
            for x in cost_list:
                if x['name'] == i['order_format']:
                    costs = i['order_count'] * x['cost']
                    price += costs
        return render(self.request, 'main/complite.html', {
            'orders': order_list,
            'cost': cost_list,
            'price': price,
            'user_info': user_info,
        })


def confirm_order(request):
    photos_list = Photo.get_user_photos(request)
    for photo in photos_list:
        user_id = photo.session_key
    added_order = None
    
    if request.method == 'POST':
        order = ConfirmOrder(
            name=request.POST['name'],
            phone=request.POST['phone'],
            delivery=request.POST['delivery'],
            address=request.POST.get('address'),
            comment=request.POST.get('comment'),
            session_key=user_id
        )
        moveFiles(request)
        order.save()
        added_order = order
        date_time = datetime.now().strftime("%m-%d-%Y %H:%M")
        photos_list = Photo.get_user_photos(request)
        for photo in photos_list:
            user_id = photo.session_key
            photo_path = os.path.dirname(photo.file.path)
            client_path = photo.file.name
            client_name = ''.join(client_path.split('/')[1])
            order_file = photo_path + '\\' + client_name + '.txt'
            
        order_log = open(order_file, mode="a", encoding="utf-8")
        order = ConfirmOrder.objects.all().filter(session_key=user_id)
        order.update(link=client_name)
        order_data = ''
        order_data += "Время заказа - " + date_time + '\n'
        order_data += "Клиент - " + added_order.name + '\n'
        order_data += "Телефон - " + added_order.phone + '\n'
        order_data += "Способ доставки - " + added_order.delivery + '\n'
        order_data += "Адрес доставки - " + str(added_order.address) + '\n'
        order_data += "Комментарии - " + added_order.comment + '\n\n'

        order_list = Orders.get_order_photos(request)

        mail_data = []

        for order in order_list:
            order_data += order.order_format + " " + \
                order.order_papier + " " + \
                str(order.order_count) + " шт" '\n'

            mail_data.append(order)

        email = SendingEmail()
        if request.user.is_authenticated:
            user_email = request.user.email
            email.sending_email(type_id=2, email=user_email,
                                order=added_order, data=mail_data)
        email.sending_email(type_id=1, order=added_order, data=mail_data)

        order_log.write(order_data)
        order_log.close()
        photos_list.delete()

        log.info('Order was confirmed for user:" %s"', photo.user)

        order_list.delete()
    return render(request, 'main/added-order.html', {'order': added_order, 'successful_submit': True})

shop/views.py
from django.shortcuts import render
from django.views.generic.base import View
from .models import ShopCardModel, ShopCardPhotos


class ProductsViewsList(View):
    def get(self, request):
        cat = ShopCardModel.objects.all()
        products = ShopCardModel.objects.all()
        photos = []
        for i in products:
            photos.append(ShopCardPhotos.objects.filter(show_id=i.id).first())
        context = {
            'products': products,
            'category': cat,
            'products_photos': photos
        }
        return render(request, 'shop/shop-page.html', context)


class ProductsViewsDetail(View):
    def get(self, request, id):
        product = ShopCardModel.objects.all().filter(id=id)
        photo = ShopCardPhotos.objects.all()
        first_photo = ShopCardPhotos.objects.filter(show_id=id).first()
        context = {
            'product': product,
            'product_photo': photo,
            'first_photo': first_photo
        }
        return render(request, 'shop/shop-page-detail.html', context)


class ProductViewsCategory(View):
    def get(self, request, category):
        products = ShopCardModel.objects.all().filter(category=category)
        cat = ShopCardModel.objects.all()
        photos = []
        for i in products:
            photos.append(ShopCardPhotos.objects.filter(show_id=i.id).first())
        context = {
            'products': products,
            'category': cat,
            'products_photos': photos
        }
        return render(request, 'shop/shop-page.html', context)

main/templates/shop/shop-page-detail.html
{% extends 'layout/default.html' %} {% load static %} {% block title %}Photo-one / {% for product in product %}{{ product.name }} {% endfor %}{% endblock title %} {% block content %}
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.umd.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="https://kit.fontawesome.com/f4b4978e47.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
        if (Swiper) {
            var swiper = new Swiper(".tovar-swiper", {
                slidesPerView: 5,
                spaceBetween: 10,
                speed: 1000,
                loop: true,
                loopedSlides: 0,
                autoplay: {
                    delay: 5000,
                },
            });
        }
    });
</script>

<main>
    <section>
        <div class="container text-center">
            <div class="breadcrumb d-flex align-items-center">
                <a href="{% url 'home' %}" class="d-inline-block px-2">Главная</a>
                <i class="fa fa-long-arrow-right d-inline-block" aria-hidden="true"></i> 
                <a href="{% url 'shop:product' %}" class="d-inline-block px-2">Все товары</a> 
                <i class="fa fa-long-arrow-right d-inline-block" aria-hidden="true"></i> 
                <p class="d-inline-block px-2">{% for product in product %}{{ product.category }}{% endfor %}</p>
            </div>
            <div class="text-center">
                <hr class="line" />
            </div>
            <div class="col d-flex justify-content-between flex-column flex-lg-row">
                <div class="detail-image col-12 col-lg-6">
                    <a href="{{ first_photo.photo.url }}">
                        <img data-fancybox="shop-page-detail" src="{{ first_photo.photo.url }}" class="card-img-top p-2" alt="...">
                    </a>
                    <div class="detai-image-row d-flex justify-content-between col px-2">
                        {% for product in product %}
                        <div class="swiper-container tovar-swiper" style="overflow: hidden">
                            <div class="swiper-wrapper">
                                {% for photo in product_photo %} {%if photo.show_id == product.id %}
                                <div class="swiper-slide slider-detail">
                                    <a href="{{ photo.photo.url }}">
                                        <img data-fancybox="shop-page-detail" src="{{ photo.photo.url }}" class="" alt="...">
                                    </a>
                                </div>
                                {% endif %} {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <div class="h-100">
                        <div class="card-body">
                            <h5 class="card-title text-start">{{ product.name }}</h5>
                            <p class="card-text text-start">Категория: {{ product.category }}</p>
                            <p class="card-text text-start">{{ product.description }}</p>
                            <p class="card-text text-start">Цена: <strong>{{ product.price }}</strong> руб.</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
    </section>
</main>

{% endblock content %}

main/templates/shop/shop-page.html
{% extends 'layout/default.html' %} {% load static %} {% block title %}Photo-one / Магазин{% endblock title %} {% block content %}

<main>
  <section>
    <div class="container text-center">
      <select data-csrf="{{ csrf_token }}" class="form-select category-select" onchange="location = this.value;">
          <option value="{% url 'shop:product' %}">Все товары</option>
          {% for cat in category %}
          <option value="{{ cat.category }}" {% for product in products %}{% if cat.category == product.category %}selected{% else %}''{% endif %}{% endfor %}>{{ cat.category }}</option>
          {% endfor %}
      </select>

      <div class="text-center">
        <hr class="line" />
      </div>
            <div class="row row-cols-1 row-cols-lg-5 g-4 row-cols-sm-3 row-cols-md-4">
            {% for product in products %}
                <div class="col shop-page">   
                <a href="{% url 'shop:detail' product.id %}">       
                  <div class="card">
                  {% for photo in products_photos %}
                  {%if photo.show_id == product.id %}
                  <div class="card-image-main p-2 mt-2">
                    <img src="{{ photo.photo.url }}" class="card-img-top" alt="...">
                    </div>
                    {% endif %}
                    {% endfor %}
                    <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <p class="card-text">{{ product.category }}</p>
                      <p class="card-text card-text-description">{{ product.description|truncatewords:7 }}</p>
                      <p class="card-text">Цена: <strong>{{ product.price }}</strong> руб.</p>
                    </div>
                  </div>
                  </a>
                </div>               
            {% endfor %}
      </div>
  </section>
</main>

{% endblock content %}

main/templates/shop/show_thumbnail.html
<a href="{{ photo.url }}">
  <img src="{{ photo.url }}" style="max-height: 200px" />
</a>