main/urls.py
from django.urls import path
from django.contrib.auth.decorators import user_passes_test
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('servises/', views.servises, name='servises'),
    path('order/', views.BasicUploadView.as_view(), name='order'),
    path('<int:id>/delete/', views.delete_photo, name='delete'),
    path('order/confirm/', views.edit_upload_form, name='confirm'),
    path('complite/', views.OrderComplite.as_view(), name='complite'),
    path('added-order/', views.confirm_order, name='added-order'),
    path('portfolio/', views.portfolio, name='portfolio'),
]

photo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('main.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import UserSignupView, LoginForm, logout_view, UserEditView

app_name = 'user'

urlpatterns = [
    path('login/', LoginForm.as_view(), name='login'),
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('<int:pk>/edit/', UserEditView.as_view(), name='edit'),
    path('logout/', logout_view, name='logout'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserModel(AbstractUser):
    city = models.CharField(max_length=64, null=True, blank=True)
    phone = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        full_name = self.get_full_name()

        if full_name:
            return f'{full_name} ({self.email})'

        return f'{self.username} ({self.email})'

    def get_pretty_name(self):
        full_name = self.get_full_name()
        if full_name:
            return full_name

        return self.username

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, PasswordInput, CharField, ValidationError
from .models import UserModel


class SignupForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваш логин'})
        self.fields['email'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваш email'})
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваш пароль'})
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Повторите ввод пароля'})


class UserEditForm(ModelForm):
    password1 = CharField(min_length=6, label='Пароль', widget=PasswordInput)
    password2 = CharField(
        min_length=6, label='Повторите ввод пароля', widget=PasswordInput)
    phone = CharField(label='Телефон')
    city = CharField(label='Адрес доставки')

    class Meta:
        model = UserModel
        fields = ('email', 'first_name', 'last_name', 'phone', 'city')

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваш email'})
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваш пароль'})
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Повторите ввод пароля'})
        self.fields['first_name'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваше имя'})
        self.fields['last_name'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваша фамилия'})
        self.fields['phone'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваш телефон'})
        self.fields['city'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Ваш адрес доставки'})

    def clean_password2(self):
        pass1 = self.cleaned_data.get('password1')
        pass2 = self.cleaned_data.get('password2')

        if len(pass1) == 0 and len(pass2) == 0:
            return pass2

        if pass1 == pass2:
            return pass2

        raise ValidationError('Пароли не совпадают')

user/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import FormView
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from .forms import SignupForm, UserEditForm
from .models import UserModel


class LoginForm(LoginView):
    template_name = 'layout/default.html'
    form_class = AuthenticationForm


class UserSignupView(FormView):
    template_name = 'user/signup.html'
    form_class = SignupForm

    def form_valid(self, form: SignupForm):
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']
        user = UserModel.objects.create_user(username, email, password)
        login(self.request, user)
        return HttpResponseRedirect('/')


class UserEditView(UpdateView):
    form_class = UserEditForm
    model = UserModel

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        user = self.get_object()
        if user != request.user:
            return HttpResponseForbidden('Доступ запрещен')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form: UserEditForm):
        password = form.cleaned_data.get('password1')
        user: UserModel = self.object
        if password:
            user.set_password(password)
            user.save()

        login(self.request, user)
        return HttpResponseRedirect('/')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

user/templates/user/login.html
<div
  class="modal fade"
  id="modal-login"
  data-backdrop="static"
  data-keyboard="false"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Вход на сайт</h4>
      </div>
      {% if user.is_anonymous %}
      <div class="modal-body">
        <div class="login-form">
          {% if form.errors %}
          <div class="text-center">
            {% for _, error in form.errors.items %}
            <strong>{{ error }}</strong>
            {% endfor %}
          </div>
          {% endif %}
          <form action="{% url 'user:login' %}" method="post">
            {% csrf_token %}
            <div class="inputs">
              {{ error }}
              <table class="inputs">
                {{ login_link.as_table }}
              </table>
            </div>
            <div class="button row justify-content-between p-2 mt-3">
              <input
                class="col-3 btn btn-primary"
                type="submit"
                value="Войти"
              />
              <a class="d-block text-end col-5" href="{% url 'user:signup' %}"
                >Не зарегистрированы?</a
              >
            </div>
          </form>
        </div>
      </div>
      {% else %}
      <p class="text-center">
        <a href="{% url 'user:edit' user.id %}">Вход в личный кабинет</a>
      </p>
      <div class="button row text-center p-2 mt-3">
        <form
          action="{% url 'user:logout' %}?next={{ request.path }}"
          method="post"
        >
          {% csrf_token %}
          <input class="col-3 btn btn-primary" type="submit" value="Выход" />
        </form>
      </div>
      {% endif %}
    </div>
  </div>
</div>

user/templates/user/signup.html
{% extends 'layout/default.html' %} {% block content %}
<div class="container">
  <div class="text-center">
    <hr class="line mt-0" />
  </div>
</div>
<div class="container col p-4">
  <h3 class="d-block text-center p-3">Регистрация на сайте</h3>

  <form action="" method="post">
    {% csrf_token %}
    <div class="inputs">
      <table class="inputs">
        {{ form.as_table }}
      </table>
    </div>
    <div class="button pt-2 text-center text-sm-start">
      <input class="btn btn-primary" type="submit" value="Зарегистрироваться" />
    </div>
  </form>
</div>

{% endblock content %}

user/templates/user/usermodel_form.html
{% extends 'layout/default.html' %} {% block content %}
<div class="container">
  <div class="text-center">
    <hr class="line mt-0" />
  </div>
</div>
<div class="container col p-4">
  <h3 class="d-block text-center p-3">Личный кабинет</h3>

  <form action="" method="post">
    {% csrf_token %}
    <div class="inputs">
      <table class="inputs">
        {{ form.as_table }}
      </table>
    </div>
    <div class="button pt-2 text-center text-sm-start">
      <input class="btn btn-primary" type="submit" value="Сохранить" />
    </div>
  </form>
</div>

{% endblock content %}